### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by mortie**

### CODE REVIEW

**Comment by mortie** [comment]
Could @NishiOwO, @BenediktMagnus, @crabbo-rave, @brightly-salty and @fabiosvm OK this? I don't know if it's legally necessary, but you do arguably have code with your copyright in here, which this PR would be re-licensing

**Comment by BenediktMagnus** [comment]
I accept the MIT license.

But I suggest to add the contributors to the copyright notice (most simply by adding "and other contributors" after your name). Regardless of what the notice says, all contributors keep their copyright. Even if it does not matter for the license grant, correctly picturing reality should be preferable.

**Comment by brightly-salty** [comment]
I accept the MIT license

**Comment by fabiosvm** [comment]
I accept the MIT license

**Comment by NishiOwO** [comment]
I consent

**Pull request merged**
