### PR TITLE
Added Phosphor

### PR DESCRIPTION
**Pull request by BenediktMagnus**
I added the [Phosphor programming language](https://github.com/PhosphorLang).
The version used is the latest release (0.2.1) which I published today.

Note that Node.js, binutils and NASM are needed as dependencies for the compiler to work. The additionally added installation of lsb-release is used for making the node installation platform-agnostic and could theoretically be removed if `DISTRO="$(lsb_release -s -c)"` is replaced with `DISTRO=jammy` (for Ubuntu 22.04) and maintained to match the used image.

### CODE REVIEW

**Comment by mortie** [comment]
Is there a reason you prefer to download with curl rather than with git? Otherwise I may just change it to download with git.

**Comment by mortie** [comment]
Also, this doesn't seem to be picking up on the standard library properly:

```
runner@e6a26a8ee40c:/app/deploy/phosphor$ bash run.sh
function main() {
writeLine('hello');
}

> phosphor-compiler@0.2.1 start
> node bin/main.js "-t" "linuxAmd64" "-s" "../phosphorStandardLibrary" "../input.ph" "../output"

../input.ph:2:9 - Error E1021: Unknown function "writeLine"
```

I tried to fix it, but I couldn't get it to work.

**Comment by BenediktMagnus** [comment]
> Is there a reason you prefer to download with curl rather than with git? Otherwise I may just change it to download with git.

Downloading the pre-compiled releases instead of checking out a git commit saves disk space and time as there are less dependencies required and no compiling needed. Besides that, it is the way a user would probably get the compiler, as it's much easier.

**Comment by BenediktMagnus** [comment]
> Also, this doesn't seem to be picking up on the standard library properly:

Oh, it seems that the hello world in the README was a bit outdated. There is an import missing. It works for me this way:
```
import 'io';

function main ()
{
    writeLine('Hello world!');
}
```

**Pull request merged**
