### PR TITLE
Update Cognate to latest commit

### PR DESCRIPTION
**Pull request by StavromulaBeta**

### CODE REVIEW

**Comment by StavromulaBeta** [comment]
Huh. Looks like the test is failing because Gwion doesn't have a dev branch any more (@fennecdjay)

**Comment by fennecdjay** [comment]
sounds correct.
i may have deleted it by mistake after the latest merge to master.
my bad.
ig tho it would be better to target said master branch.
sorry for the inconvenience

**Comment by StavromulaBeta** [comment]
Oop it looks like the commit that Cthulhu is using doesn't exist any more either. @apache-hb could you suggest a substitute?

**Comment by apache-hb** [comment]
Oh, terribly sorry about this. [18cb70e5fdd25bc589bb62540b6f6f6556bdba1f](https://github.com/apache-hb/cthulhu/tree/18cb70e5fdd25bc589bb62540b6f6f6556bdba1f) on the master branch should be stable.

**Comment by StavromulaBeta** [comment]
@apache-hb Switched it to use that commit, still seems to be throwing some errors:

```
The Meson build system
Version: 0.61.2
Source dir: /app/work/cthulhu/cthulhu
Build dir: /app/work/cthulhu/cthulhu/build
Build type: native build
meson.build:1:0: ERROR: project got unknown keyword arguments "license_files"
A full log can be found at /app/work/cthulhu/cthulhu/build/meson-logs/meson-log.txt
error building at STEP "RUN ./scripts/compile-all.sh": error while running runtime: exit status 1
```

**Comment by apache-hb** [comment]
It requires meson 1.3 to build, strange that meson isnt reporting that in the error

**Comment by StavromulaBeta** [comment]
Huh it looks like half the langs aren't building for some reason or another

**Pull request closed without merging**
